/**
 * ╔══════════════════════════════════════════════════════════════════════════╗
 * ║  CROWN — Anti-Drift Constants (§1.2.4 — The 9 Anti-Drift Locks)          ║
 * ║  Phase 1.2 · Constitutional Level — Above All PRD Sections               ║
 * ║  Owner: Ail Noor Alam (Founder) · Chandigarh · May 2026                 ║
 * ╠══════════════════════════════════════════════════════════════════════════╣
 * ║  THESE NINE RULES CANNOT BE OVERRIDDEN BY:                               ║
 * ║  - Any future PRD                                                        ║
 * ║  - Founder mood                                                          ║
 * ║  - Investor pressure                                                     ║
 * ║  - "Let's make an exception this once"                                   ║
 * ║                                                                          ║
 * ║  Each constant is lint-checked on every PR.                              ║
 * ║  Any code that conditionally checks ANTI_DRIFT.X === false to ENABLE     ║
 * ║  a forbidden behavior is a CRITICAL PR block.                            ║
 * ╚══════════════════════════════════════════════════════════════════════════╝
 *
 * Usage:
 *   import { ANTI_DRIFT } from '@/lib/anti-drift-constants';
 *
 *   // In message delivery logic:
 *   assert(ANTI_DRIFT.LAKH_REACH_DELIVERY === true,
 *     'Every message must reach every active user. No algorithm gate.');
 *
 *   // In credit creation logic:
 *   if (ANTI_DRIFT.FOUNDER_FUNDED_CREDITS) {
 *     throw new Error('ANTI_DRIFT VIOLATION: Founder cannot fund credits');
 *   }
 */

// ═══════════════════════════════════════════════════════════════════════════
// § 1 — THE 9 ANTI-DRIFT LOCKS (Exhaustive — No New Locks Without PRD Amendment)
// ═══════════════════════════════════════════════════════════════════════════

export const ANTI_DRIFT = Object.freeze({

  /**
   * LOCK #1 — The 1-Lakh Reach Promise
   *
   * Every message reaches every active user in its scope.
   * NO algorithm. NO follower gate. Equal voice ALWAYS.
   *
   * Implementation rule: Message delivery pipeline must fan out to ALL
   * active subscribers in the Firestore/Pusher channel — never filter by
   * follower count, trust score, or any other metric.
   *
   * Why immutable: Without this, CROWN is just another Discord.
   */
  LAKH_REACH_DELIVERY: true as const,

  /**
   * LOCK #2 — Zero-Credit Founder Rule
   *
   * The Founder NEVER gives out a single Credit, EVER.
   * - No welcome Credits
   * - No streak Credits
   * - No referral Credits
   * - No challenge Credits
   * - No first-message Credits
   * - No daily-login Credits
   *
   * Every Credit in circulation was purchased by a real user with real money
   * OR transferred between users through bidding.
   * CROWN extracts only fees on transfers — never creates Credits from nothing.
   *
   * Why immutable: Without this, CROWN is a deposit-taking scheme requiring
   * RBI/SEBI/FinCEN/EU e-money licenses. Insolvency at scale.
   */
  FOUNDER_FUNDED_CREDITS: false as const,

  /**
   * LOCK #3 — No Real Currency Symbol In-App
   *
   * NEVER render ₹, $, €, £, ¥, or any real currency symbol anywhere
   * except the Cashout screen.
   *
   * In-app: Credits only.
   * Real money appears ONLY on the Cashout screen, in the user's local currency.
   *
   * Why immutable: App Store policy + tax authority scrutiny in every jurisdiction.
   */
  CURRENCY_SYMBOL_INAPP: false as const,

  /**
   * LOCK #4 — Server-Side Rate Limits Only
   *
   * Rate limits are ALWAYS enforced server-side (Redis Sorted Set).
   * Client-side = NO limits.
   *
   * Rationale: Client-side limits are trivially bypassed. A single Sybil
   * attacker can dump 1L messages from one account if only the client checks.
   *
   * Implementation: All rate limit checks happen in API routes / Cloud Functions
   * BEFORE any message is written to Firestore/Pusher.
   */
  CLIENT_SIDE_RATE_LIMIT: false as const,

  /**
   * LOCK #5 — AI Is Always Labeled
   *
   * EVERY AI Companion message, EVERY Heritage Message generated by AI,
   * EVERY AI-translated string MUST carry the "🤖 AI" badge.
   * ALWAYS. No exceptions. Never hidden. Never styled to look human.
   *
   * Why immutable: DSA + DPDP + Apple App Privacy compliance + user trust.
   * See: §1.2.3 Rule 11 — AI Companions Don't Pose As Friends.
   */
  AI_LABEL_REQUIRED: true as const,

  /**
   * LOCK #6 — DMs Are End-to-End Encrypted
   *
   * ALL Direct Messages are encrypted with libsignal (Signal Protocol).
   * The server architecturally CANNOT read DMs.
   * No AI reads DMs. No moderation reads DMs.
   * The system acts ONLY when a user files a report.
   *
   * Why immutable: DPDP Act 2023 illegal otherwise. WhatsApp DNA.
   * See: §1.2.3 Rule 1 — Private DMs Are a Closed Room.
   */
  DM_E2E_ENCRYPTED: true as const,

  /**
   * LOCK #7 — Title Power Is Ceremonial
   *
   * No title-holder (BARON / Mayor (VICEROY) / SOVEREIGN / IMPERATOR) can:
   * - Ban a user
   * - Mute a user
   * - Kick a user from a room
   * - DM-flood a user
   *
   * Title powers: ONE pinned message per day + a slice of cycle bid fees.
   * That is the complete and exhaustive list of title-holder powers.
   *
   * Why immutable: Power = corruption = lawsuits = death.
   */
  TITLE_HOLDER_BANS_OK: false as const,

  /**
   * LOCK #8 — Hard Push Notification Cap
   *
   * MAXIMUM 3 emotional push notifications per user per day.
   * Server-side enforced (Redis counter, 24h window).
   * Transactional pushes (OTP, payment confirmed, etc.) are unlimited.
   * Cycle Decision push ("you're the Merit Winner") bypasses cap ONLY with opt-in.
   *
   * Why immutable: Day-1 retention vs uninstall-storm.
   * Android: can further reduce cap based on user dismissal rate signals.
   */
  EMOTIONAL_PUSH_CAP: 3 as const,

  /**
   * LOCK #9 — PSS Stage-Gated Launch
   *
   * "Day 1 Global" is the ARCHITECTURE, NOT the launch.
   * The architecture supports every country and every city on Earth.
   * The LAUNCH is local — Stage 2 Chandigarh on Day 1.
   * PSS Stage advancement is the ONLY rollout vector.
   *
   * Why immutable: A sole engineer cannot operate 195-country compliance,
   * moderation, and on-call for free. Stage gating = survival.
   * See: §1.2.2 Non-Negotiable #3 — PSS Stage-gated rollout.
   */
  DAY_1_GLOBAL_LAUNCH: false as const,

} as const);

// ═══════════════════════════════════════════════════════════════════════════
// § 2 — RATE LIMIT THRESHOLDS (Lock #4 — Server-Side Only)
// These constants define the server-side thresholds.
// Client NEVER enforces these — server validates every request.
// ═══════════════════════════════════════════════════════════════════════════

export const RATE_LIMITS = Object.freeze({

  /**
   * Message send — per user per second.
   * Human typing 4 short messages in 10 seconds is NORMAL.
   * Rate limits trigger only on superhuman/machine speed.
   * §1.2.3 Rule 6 — Welcome New Users, Don't Cage Them.
   */
  MSG_PER_SECOND_MAX: 5 as const,

  /**
   * Message send — sustained burst window (seconds).
   * If a user exceeds MSG_PER_SECOND_MAX for this many consecutive seconds,
   * they are rate-limited (not banned — slow-mode only).
   */
  MSG_BURST_WINDOW_SEC: 10 as const,

  /**
   * Auth attempts — per phone number per 15 minutes.
   * Triggers OTP verification lock after this many failed attempts.
   */
  AUTH_ATTEMPTS_PER_15MIN: 5 as const,

  /**
   * Bid placement — per user per minute.
   * Financial operation — strict rate limit.
   */
  BID_PER_MINUTE: 5 as const,

  /**
   * Cashout requests — per user per day.
   * Financial operation — strict limit.
   */
  CASHOUT_PER_DAY: 3 as const,

  /**
   * Emotional push notifications — per user per day.
   * Hard cap per Anti-Drift Lock #8.
   * Enforced at notification dispatch time in Cloud Function.
   */
  EMOTIONAL_PUSH_PER_DAY: ANTI_DRIFT.EMOTIONAL_PUSH_CAP,

} as const);

// ═══════════════════════════════════════════════════════════════════════════
// § 3 — SOLVENCY RATIOS (§1.2.5 — Treasury Daily Track)
// ═══════════════════════════════════════════════════════════════════════════

export const SOLVENCY = Object.freeze({
  /**
   * Cashout Liability Ratio threshold.
   * Formula: Outstanding Credits in wallets × Cashout rate ÷ Cash on hand
   * If ratio > 50% for 2 consecutive months → Emergency Controls activate.
   */
  CASHOUT_LIABILITY_RATIO_MAX: 0.50 as const,

  /**
   * Net Margin per IAP threshold.
   * Formula: (Gross IAP − App Store cut − Cashout liability − processor fees) ÷ Gross IAP
   * Must be > 20% average AND > 0% every transaction.
   * If 0% on any transaction → BLOCK the transaction.
   */
  NET_MARGIN_MIN: 0.20 as const,
  NET_MARGIN_PER_TX_MIN: 0.001 as const,  // > 0% per transaction (0.1% min practical floor)

  /**
   * The Solvency Rule (§1.2.1 Law 3):
   * The cashout rate per 100 Credits is ALWAYS strictly less than
   * the purchase price of 100 Credits.
   * This constant is the mathematical proof that CROWN cannot go bankrupt:
   * true = cashout rate < purchase rate (non-negotiable invariant).
   */
  CASHOUT_LESS_THAN_PURCHASE: true as const,

  /**
   * Cost-to-Concurrent-User thresholds (₹) per PSS stage.
   * Monthly infra ₹ ÷ Avg peak concurrent users.
   * If stage cost > threshold for 2 consecutive months → scale plan required.
   */
  COST_PER_CCU_MAX: {
    STAGE_2: 0.5,   // < ₹0.5 per CCU
    STAGE_3: 1.0,   // < ₹1.0 per CCU
    STAGE_4: 2.0,   // < ₹2.0 per CCU
    STAGE_5: 4.0,   // < ₹4.0 per CCU
  } as const,

} as const);

// ═══════════════════════════════════════════════════════════════════════════
// § 4 — CONTENT POLICY LIMITS (§1.2.3 Rule 3 — AI Is a Security Guard, Not a Dictator)
// ═══════════════════════════════════════════════════════════════════════════

export const CONTENT_POLICY = Object.freeze({
  /**
   * AI moderation triggers ONLY for extreme content.
   * NOT for: casual disagreements, rough banter, "low quality" messages.
   * §1.2.3 Rule 2 — Public Chats Allow "Good Morning".
   */
  AI_MODERATE_ONLY_EXTREME: true as const,

  /**
   * Content categories that trigger AI moderation (exhaustive list):
   * - incitement to violence
   * - terrorism
   * - child sexual abuse material (CSAM)
   * - extreme hate speech (genocide, ethnic cleansing calls)
   *
   * NOT included (AI does NOT moderate):
   * - casual conversation
   * - light arguments
   * - rough banter
   * - disagreements
   * - single emojis
   * - "GM" messages
   */
  EXTREME_CONTENT_CATEGORIES: [
    'incitement_violence',
    'terrorism',
    'csam',
    'extreme_hate_speech',
  ] as const,

  /**
   * Reports needed to escalate to human review.
   * Three or more reports on the same content → human review queue.
   * §1.2.3 Rule 12 — The Crowd Is The Court.
   */
  REPORTS_FOR_HUMAN_REVIEW: 3 as const,

  /**
   * Shadow ban policy — NEVER.
   * Anti-Drift Lock #5 enforcement: if a restriction is applied,
   * the user ALWAYS sees it on their own screen with reason + appeal path.
   * §1.2.3 Rule 5 — No Shadow Bans.
   */
  SHADOW_BAN_ALLOWED: false as const,

  /**
   * Account ban policy — ONLY for crime.
   * §1.2.3 Rule 4 — No Account Bans For Talking.
   * Permanent suspension ONLY for:
   * (a) hacking/exploitation
   * (b) mass automated spam
   * (c) confirmed fraud or extreme illegal content
   */
  ACCOUNT_BAN_FOR_TALKING: false as const,

} as const);

// ═══════════════════════════════════════════════════════════════════════════
// § 5 — UX INVARIANTS (§1.2.3 User-First Rules — Operationalization)
// ═══════════════════════════════════════════════════════════════════════════

export const UX_INVARIANTS = Object.freeze({
  /**
   * Rule 7 — No Captchas During The CROWN Moment.
   * When a user's message is going viral, NO captcha, OTP prompt,
   * or human-verification puzzle appears. Verification can wait.
   */
  NO_CAPTCHA_DURING_CROWN_MOMENT: true as const,

  /**
   * Rule 8 — Breaks Are Allowed.
   * If a user does not open the app for 30/60/90 days:
   * - Trust Score does NOT drop
   * - Rank Score from past cycles is preserved
   * - They are welcomed back exactly as they left
   */
  INACTIVITY_PENALTY: false as const,

  /**
   * Rule 9 — Edits Are Not Punished.
   * Typos and clarifications NEVER cost Trust Score.
   * Edited message is re-scanned by AI Gatekeeper — that is the only check.
   */
  EDIT_PENALTY: false as const,

  /**
   * Rule 6 — Welcome New Users, Don't Cage Them.
   * A human typing 4 short messages in 10 seconds is NORMAL behavior.
   * Rate limits trigger ONLY on superhuman/machine speed.
   */
  NORMAL_BURST_MESSAGES: 4 as const,
  NORMAL_BURST_WINDOW_SEC: 10 as const,

  /**
   * Minimum inactivity days before ANY penalty could theoretically apply.
   * Currently INFINITY (INACTIVITY_PENALTY = false).
   * This constant exists for future audit clarity.
   */
  MIN_INACTIVITY_PENALTY_DAYS: Infinity as const,

  /**
   * Sub-Room renewal policy.
   * Rule 10 — Sub-Rooms Are Not Killed While Alive.
   * Hard limit: 7 renewals = 1 week max.
   */
  SUB_ROOM_MAX_RENEWALS: 7 as const,
  SUB_ROOM_DURATION_HOURS: 24 as const,

  /**
   * AI Companion silence threshold.
   * The instant 5+ real users are active in a sector, AI Companions go silent.
   * §1.2.3 Rule 11.
   */
  AI_COMPANION_SILENCE_THRESHOLD: 5 as const,

  /**
   * Peek mode — read without account.
   * §1.2.2 Non-Negotiable #6.
   * A user can read any city, any sector, anywhere WITHOUT signing up.
   * Signup required ONLY to: send messages, react, follow, DM, bid, cash out.
   */
  PEEK_ALLOWED_WITHOUT_AUTH: true as const,

} as const);

// ═══════════════════════════════════════════════════════════════════════════
// § 6 — TYPE EXPORTS
// ═══════════════════════════════════════════════════════════════════════════

export type AntiDrift      = typeof ANTI_DRIFT;
export type RateLimitKey   = keyof typeof RATE_LIMITS;
export type SolvencyConfig = typeof SOLVENCY;
export type ContentPolicy  = typeof CONTENT_POLICY;
export type UxInvariant    = keyof typeof UX_INVARIANTS;
